micronaut:
  application:
    name: kasaDoKodigo
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/codehouse
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    dialect: MARIADB
jpa.default.properties.hibernate.hbm2ddl.auto: update
